-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT app_user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    email_user character varying(100) COLLATE pg_catalog."default",
    name_user character varying(100) COLLATE pg_catalog."default",
    phone_user character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer_name character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hall
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default",
    seat_count integer NOT NULL,
    theater_id bigint,
    CONSTRAINT hall_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.performance
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    age_restriction integer NOT NULL,
    description character varying(1000) COLLATE pg_catalog."default",
    duration integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT performance_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchase
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    purchase_date timestamp(6) without time zone,
    total_amount double precision NOT NULL,
    customer_id bigint,
    CONSTRAINT purchase_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchase_ticket
(
    purchase_id bigint NOT NULL,
    ticket_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.role
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.show
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    show_date date,
    show_time time(6) without time zone,
    hall_id bigint,
    performance_id bigint,
    CONSTRAINT show_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.theater
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(200) COLLATE pg_catalog."default",
    name_theater character varying(100) COLLATE pg_catalog."default",
    website character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT theater_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    price double precision NOT NULL,
    seat_number integer NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    show_id bigint,
    CONSTRAINT ticket_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE IF EXISTS public.hall
    ADD CONSTRAINT fkjwgc3yb123rpbgf6o85rlw897 FOREIGN KEY (theater_id)
    REFERENCES public.theater (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fk2pehe23hwdcyql94c531rbf70 FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_ticket
    ADD CONSTRAINT fkg1scbgahrl95j0u8b35a2w5t8 FOREIGN KEY (ticket_id)
    REFERENCES public.ticket (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_ticket
    ADD CONSTRAINT fkilpfm45l53eyf5klevpg2p7q1 FOREIGN KEY (purchase_id)
    REFERENCES public.purchase (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.show
    ADD CONSTRAINT fkcq72f5py0v04blf8b510k4n2b FOREIGN KEY (hall_id)
    REFERENCES public.hall (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.show
    ADD CONSTRAINT fknakbh1nog2643m01da8s84x92 FOREIGN KEY (performance_id)
    REFERENCES public.performance (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket
    ADD CONSTRAINT fkd142jb6gj0dhu38tyf2bn5tc FOREIGN KEY (show_id)
    REFERENCES public.show (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users_roles
    ADD CONSTRAINT fkt4v0rrweyk393bdgt107vdx0x FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users_roles
    ADD CONSTRAINT fkt8grfrdse9vcbf5iarw2f3fut FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;